import type { NextPage } from "next";
import Head from "next/head";
import Dashboard from "../components/Dashboard";
import LoginForm from "../components/Login-form";
import SignUp from "../components/SignUp";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title> WesternUnion/WU </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
                <link
                    href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css'
                    rel='stylesheet'
                    integrity='sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3'
                    crossorigin='anonymous'
                ></link>

                <script
                    src='https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js'
                    integrity='sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj'
                    crossorigin='anonymous'
                />
                <script
                    src='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js'
                    integrity='sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p'
                    crossorigin='anonymous'
                ></script>
            </Head>

            <LoginForm />
        </div>
    );
};

export default Home;
