import classNames from 'classnames';
import Head from 'next/head';
import Link from 'next/link';
import {user,partners} from '../mock_data.json';
import styles from '../styles/Home.module.css';
import { useState } from 'react';

export default function Home() {
    const [searchTerm, setSearchTerm] = useState('')
	return (
		<div className={styles.container}>
			<Head>
				<title>Accounts</title>
                <meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
					integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"
					crossorigin="anonymous"
				/>
				<script
					src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
					integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
					crossorigin="anonymous"
				/>
				<script
					src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
					integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
					crossorigin="anonymous"
				/>
			</Head>

	    <div>
            <h2>My Accounts</h2>
		</div>
        <div className='data_filter'>
            <input type = {'text'} placeholder = "   Search....." onChange= { event =>{setSearchTerm(event.target.value)}}/>
            {user.map((val : any, key : any) => {
                return(
                <div className='user' key = {key}>
                    <p>{val.firstName}</p>
                </div>
                );
            })}
            {partners.map((val : any, key : any) => {
                return(
                <div className='user' key = {key}>
                    <p>{val.name}</p>
                </div>
                );
            })}
        </div>
        </div>
	);
}
